[project]
id = "wcatkrxaxgucrtcqneik"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.migrations]
schema_paths = ["./migrations"]

[auth]
enabled = true
email.enable_signup = true
email.double_confirm_changes = true
email.enable_confirmations = false

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
